export const FETCH_CARS_REQUEST = 'FETCH_CARS_REQUEST';
export const FETCH_CARS_SUCCESS = 'FETCH_CARS_SUCCESS';
export const FETCH_CARS_FAILURE = 'FETCH_CARS_FAILURE';
export const FILTER_CARS_BY_PARAMS = 'FILTER_CARS_BY_PARAMS';
export const CHANGE_PAGE = 'CHANGE_PAGE';
